const express = require('express')
const router = express.Router()
const adminController = require('../controllers/admin')
router.route('/dashboard').get(adminController.dashboard)
router.route('/blog').get(adminController.blog)
router.route('/comments').get(adminController.comments)
router.route('/article')
    .get(adminController.showArticleForm)
    .post(adminController.saveArticle)
router.route('/category')
    .post(adminController.saveCategory)
module.exports = router